[package]
name = "ax_slab_allocator"
version = "0.3.2-preview.1"
edition = "2021"
authors = ["Robert Węcławski <r.weclawski@gmail.com>", "Yiren Zhang <zyr_ms@outlook.com>", "Yu Chen <yuchen@tsinghua.edu.cn>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/arceos-org/slab_allocator"
homepage = "https://github.com/arceos-org/slab_allocator"
documentation = "https://docs.rs/ax_slab_allocator"

description = "Slab allocator for `no_std` systems. Uses multiple slabs with blocks of different sizes and a linked list for blocks larger than 4096 bytes"
keywords = ["slab", "allocator", "no_std", "heap", "kernel"]

[dependencies]
buddy_system_allocator = { version = "0.10", default-features = false }
